last 30

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,6 +36,22 @@ jobs:
           docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
           docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
 
+      - name: Save Docker image as tar file
+        run: |
+          mkdir -p ./docker-images  # Crear la carpeta donde se guardará la imagen tar
+          docker save -o ./docker-images/image.tar $ECR_REPOSITORY:$IMAGE_TAG
+        # Guardamos el archivo tar en la carpeta ./docker-images
+
+      - name: Check if image.tar exists
+        run: |
+          if [ -f ./docker-images/image.tar ]; then
+            echo "image.tar found."
+          else
+            echo "image.tar not found!"
+            exit 1
+          fi
+        # Verificar si el archivo image.tar se creó correctamente
+
   scan-image:
     needs: build-and-push
     runs-on: ubuntu-latest
@@ -51,6 +67,7 @@ jobs:
           MALWARE_SCAN: true
           SECRETS_SCAN: true
           IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
+          LOCAL_IMAGE_TARBALL: ./docker-images/image.tar  # Ruta correcta para el archivo tar
           MAX_TOTAL: 5
           MAX_CRITICAL: 1
           MAX_HIGH: 1
